// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: examples/validation.proto

package examples

import (
	_ "github.com/cybozu/protobuf/cybozu/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enums_Enum int32

const (
	Enums_E_UNSPECIFIED Enums_Enum = 0
	Enums_E_VAL1        Enums_Enum = 1
	Enums_E_VAL100      Enums_Enum = 100
)

// Enum value maps for Enums_Enum.
var (
	Enums_Enum_name = map[int32]string{
		0:   "E_UNSPECIFIED",
		1:   "E_VAL1",
		100: "E_VAL100",
	}
	Enums_Enum_value = map[string]int32{
		"E_UNSPECIFIED": 0,
		"E_VAL1":        1,
		"E_VAL100":      100,
	}
)

func (x Enums_Enum) Enum() *Enums_Enum {
	p := new(Enums_Enum)
	*p = x
	return p
}

func (x Enums_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Enums_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_validation_proto_enumTypes[0].Descriptor()
}

func (Enums_Enum) Type() protoreflect.EnumType {
	return &file_examples_validation_proto_enumTypes[0]
}

func (x Enums_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Enums_Enum.Descriptor instead.
func (Enums_Enum) EnumDescriptor() ([]byte, []int) {
	return file_examples_validation_proto_rawDescGZIP(), []int{6, 0}
}

// This message is marked ignored, so no validation method is generated.
type Ignored struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foo           string                 `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar           int32                  `protobuf:"varint,2,opt,name=bar,proto3" json:"bar,omitempty"` // no effect
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ignored) Reset() {
	*x = Ignored{}
	mi := &file_examples_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ignored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ignored) ProtoMessage() {}

func (x *Ignored) ProtoReflect() protoreflect.Message {
	mi := &file_examples_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ignored.ProtoReflect.Descriptor instead.
func (*Ignored) Descriptor() ([]byte, []int) {
	return file_examples_validation_proto_rawDescGZIP(), []int{0}
}

func (x *Ignored) GetFoo() string {
	if x != nil {
		return x.Foo
	}
	return ""
}

func (x *Ignored) GetBar() int32 {
	if x != nil {
		return x.Bar
	}
	return 0
}

// All scalar types can have constraint rules except for bools.
type Scalars struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Float         float32                `protobuf:"fixed32,1,opt,name=float,proto3" json:"float,omitempty"`
	Double        float64                `protobuf:"fixed64,2,opt,name=double,proto3" json:"double,omitempty"`
	Int32         int32                  `protobuf:"varint,3,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64         int64                  `protobuf:"varint,4,opt,name=int64,proto3" json:"int64,omitempty"`
	Uint32        uint32                 `protobuf:"varint,5,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64        uint64                 `protobuf:"varint,6,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Sint32        int32                  `protobuf:"zigzag32,7,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64        int64                  `protobuf:"zigzag64,8,opt,name=sint64,proto3" json:"sint64,omitempty"`
	Fixed32       uint32                 `protobuf:"fixed32,9,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	Fixed64       uint64                 `protobuf:"fixed64,10,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	Sfixed32      int32                  `protobuf:"fixed32,11,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	Sfixed64      int64                  `protobuf:"fixed64,12,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Bool          bool                   `protobuf:"varint,13,opt,name=bool,proto3" json:"bool,omitempty"` // no available rules for bools
	String_       string                 `protobuf:"bytes,14,opt,name=string,proto3" json:"string,omitempty"`
	Bytes         []byte                 `protobuf:"bytes,15,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scalars) Reset() {
	*x = Scalars{}
	mi := &file_examples_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scalars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scalars) ProtoMessage() {}

func (x *Scalars) ProtoReflect() protoreflect.Message {
	mi := &file_examples_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scalars.ProtoReflect.Descriptor instead.
func (*Scalars) Descriptor() ([]byte, []int) {
	return file_examples_validation_proto_rawDescGZIP(), []int{1}
}

func (x *Scalars) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *Scalars) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

func (x *Scalars) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *Scalars) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *Scalars) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *Scalars) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *Scalars) GetSint32() int32 {
	if x != nil {
		return x.Sint32
	}
	return 0
}

func (x *Scalars) GetSint64() int64 {
	if x != nil {
		return x.Sint64
	}
	return 0
}

func (x *Scalars) GetFixed32() uint32 {
	if x != nil {
		return x.Fixed32
	}
	return 0
}

func (x *Scalars) GetFixed64() uint64 {
	if x != nil {
		return x.Fixed64
	}
	return 0
}

func (x *Scalars) GetSfixed32() int32 {
	if x != nil {
		return x.Sfixed32
	}
	return 0
}

func (x *Scalars) GetSfixed64() int64 {
	if x != nil {
		return x.Sfixed64
	}
	return 0
}

func (x *Scalars) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *Scalars) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *Scalars) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// rules for optional fields are enforced only if the field is set.
type OptionalScalars struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Float         *float32               `protobuf:"fixed32,1,opt,name=float,proto3,oneof" json:"float,omitempty"`
	Double        *float64               `protobuf:"fixed64,2,opt,name=double,proto3,oneof" json:"double,omitempty"`
	Int32         *int32                 `protobuf:"varint,3,opt,name=int32,proto3,oneof" json:"int32,omitempty"`
	Int64         *int64                 `protobuf:"varint,4,opt,name=int64,proto3,oneof" json:"int64,omitempty"`
	Uint32        *uint32                `protobuf:"varint,5,opt,name=uint32,proto3,oneof" json:"uint32,omitempty"`
	Uint64        *uint64                `protobuf:"varint,6,opt,name=uint64,proto3,oneof" json:"uint64,omitempty"`
	Sint32        *int32                 `protobuf:"zigzag32,7,opt,name=sint32,proto3,oneof" json:"sint32,omitempty"`
	Sint64        *int64                 `protobuf:"zigzag64,8,opt,name=sint64,proto3,oneof" json:"sint64,omitempty"`
	Fixed32       *uint32                `protobuf:"fixed32,9,opt,name=fixed32,proto3,oneof" json:"fixed32,omitempty"`
	Fixed64       *uint64                `protobuf:"fixed64,10,opt,name=fixed64,proto3,oneof" json:"fixed64,omitempty"`
	Sfixed32      *int32                 `protobuf:"fixed32,11,opt,name=sfixed32,proto3,oneof" json:"sfixed32,omitempty"`
	Sfixed64      *int64                 `protobuf:"fixed64,12,opt,name=sfixed64,proto3,oneof" json:"sfixed64,omitempty"`
	Bool          *bool                  `protobuf:"varint,13,opt,name=bool,proto3,oneof" json:"bool,omitempty"` // no available rules for bool
	String_       *string                `protobuf:"bytes,14,opt,name=string,proto3,oneof" json:"string,omitempty"`
	Bytes         []byte                 `protobuf:"bytes,15,opt,name=bytes,proto3,oneof" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalScalars) Reset() {
	*x = OptionalScalars{}
	mi := &file_examples_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalScalars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalScalars) ProtoMessage() {}

func (x *OptionalScalars) ProtoReflect() protoreflect.Message {
	mi := &file_examples_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalScalars.ProtoReflect.Descriptor instead.
func (*OptionalScalars) Descriptor() ([]byte, []int) {
	return file_examples_validation_proto_rawDescGZIP(), []int{2}
}

func (x *OptionalScalars) GetFloat() float32 {
	if x != nil && x.Float != nil {
		return *x.Float
	}
	return 0
}

func (x *OptionalScalars) GetDouble() float64 {
	if x != nil && x.Double != nil {
		return *x.Double
	}
	return 0
}

func (x *OptionalScalars) GetInt32() int32 {
	if x != nil && x.Int32 != nil {
		return *x.Int32
	}
	return 0
}

func (x *OptionalScalars) GetInt64() int64 {
	if x != nil && x.Int64 != nil {
		return *x.Int64
	}
	return 0
}

func (x *OptionalScalars) GetUint32() uint32 {
	if x != nil && x.Uint32 != nil {
		return *x.Uint32
	}
	return 0
}

func (x *OptionalScalars) GetUint64() uint64 {
	if x != nil && x.Uint64 != nil {
		return *x.Uint64
	}
	return 0
}

func (x *OptionalScalars) GetSint32() int32 {
	if x != nil && x.Sint32 != nil {
		return *x.Sint32
	}
	return 0
}

func (x *OptionalScalars) GetSint64() int64 {
	if x != nil && x.Sint64 != nil {
		return *x.Sint64
	}
	return 0
}

func (x *OptionalScalars) GetFixed32() uint32 {
	if x != nil && x.Fixed32 != nil {
		return *x.Fixed32
	}
	return 0
}

func (x *OptionalScalars) GetFixed64() uint64 {
	if x != nil && x.Fixed64 != nil {
		return *x.Fixed64
	}
	return 0
}

func (x *OptionalScalars) GetSfixed32() int32 {
	if x != nil && x.Sfixed32 != nil {
		return *x.Sfixed32
	}
	return 0
}

func (x *OptionalScalars) GetSfixed64() int64 {
	if x != nil && x.Sfixed64 != nil {
		return *x.Sfixed64
	}
	return 0
}

func (x *OptionalScalars) GetBool() bool {
	if x != nil && x.Bool != nil {
		return *x.Bool
	}
	return false
}

func (x *OptionalScalars) GetString_() string {
	if x != nil && x.String_ != nil {
		return *x.String_
	}
	return ""
}

func (x *OptionalScalars) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type RepeatedScalars struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// a repeated field can specify `repeated` constraints like this
	Float []float32 `protobuf:"fixed32,1,rep,packed,name=float,proto3" json:"float,omitempty"`
	// or this
	Double []float64 `protobuf:"fixed64,2,rep,packed,name=double,proto3" json:"double,omitempty"`
	// or this.
	String_       []string `protobuf:"bytes,3,rep,name=string,proto3" json:"string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedScalars) Reset() {
	*x = RepeatedScalars{}
	mi := &file_examples_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedScalars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedScalars) ProtoMessage() {}

func (x *RepeatedScalars) ProtoReflect() protoreflect.Message {
	mi := &file_examples_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedScalars.ProtoReflect.Descriptor instead.
func (*RepeatedScalars) Descriptor() ([]byte, []int) {
	return file_examples_validation_proto_rawDescGZIP(), []int{3}
}

func (x *RepeatedScalars) GetFloat() []float32 {
	if x != nil {
		return x.Float
	}
	return nil
}

func (x *RepeatedScalars) GetDouble() []float64 {
	if x != nil {
		return x.Double
	}
	return nil
}

func (x *RepeatedScalars) GetString_() []string {
	if x != nil {
		return x.String_
	}
	return nil
}

// Strings have the richest set of constraint rules.
type Strings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NFC normalization is applied if no options are given.
	S1 string `protobuf:"bytes,1,opt,name=s1,proto3" json:"s1,omitempty"`
	// normalize into the NFD form.
	S2 string `protobuf:"bytes,2,opt,name=s2,proto3" json:"s2,omitempty"`
	// enforce the minimum length of the string if the string is NOT empty.
	// This check is done after NFC normalization.
	S3 string `protobuf:"bytes,3,opt,name=s3,proto3" json:"s3,omitempty"`
	// normalize and validate the string with a PRECIS profile.
	S4 string `protobuf:"bytes,4,opt,name=s4,proto3" json:"s4,omitempty"`
	// normalize and validate the string with a PRECIS profile.
	S5 string `protobuf:"bytes,5,opt,name=s5,proto3" json:"s5,omitempty"`
	// normalize and validate the string with a PRECIS profile.
	S6 string `protobuf:"bytes,6,opt,name=s6,proto3" json:"s6,omitempty"`
	// normalize and validate the string with a PRECIS profile.
	S7 string `protobuf:"bytes,7,opt,name=s7,proto3" json:"s7,omitempty"`
	// enforce that the string matches a regular expression. The regular expression syntax is RE2.
	// See https://github.com/google/re2/wiki/Syntax
	S8 string `protobuf:"bytes,8,opt,name=s8,proto3" json:"s8,omitempty"`
	// enforce that the string is a valid email address as defined in RFC 5322.
	S9 string `protobuf:"bytes,9,opt,name=s9,proto3" json:"s9,omitempty"`
	// enforce that the string is a valid URI as defined in RFC 3986.
	// The string will also be canonicalized.
	S10 string `protobuf:"bytes,10,opt,name=s10,proto3" json:"s10,omitempty"`
	// enforce that the string is a valid telephone number as defined by E.164.
	// An example is "+81-80-0000-0000".
	S11           string `protobuf:"bytes,11,opt,name=s11,proto3" json:"s11,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Strings) Reset() {
	*x = Strings{}
	mi := &file_examples_validation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Strings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strings) ProtoMessage() {}

func (x *Strings) ProtoReflect() protoreflect.Message {
	mi := &file_examples_validation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strings.ProtoReflect.Descriptor instead.
func (*Strings) Descriptor() ([]byte, []int) {
	return file_examples_validation_proto_rawDescGZIP(), []int{4}
}

func (x *Strings) GetS1() string {
	if x != nil {
		return x.S1
	}
	return ""
}

func (x *Strings) GetS2() string {
	if x != nil {
		return x.S2
	}
	return ""
}

func (x *Strings) GetS3() string {
	if x != nil {
		return x.S3
	}
	return ""
}

func (x *Strings) GetS4() string {
	if x != nil {
		return x.S4
	}
	return ""
}

func (x *Strings) GetS5() string {
	if x != nil {
		return x.S5
	}
	return ""
}

func (x *Strings) GetS6() string {
	if x != nil {
		return x.S6
	}
	return ""
}

func (x *Strings) GetS7() string {
	if x != nil {
		return x.S7
	}
	return ""
}

func (x *Strings) GetS8() string {
	if x != nil {
		return x.S8
	}
	return ""
}

func (x *Strings) GetS9() string {
	if x != nil {
		return x.S9
	}
	return ""
}

func (x *Strings) GetS10() string {
	if x != nil {
		return x.S10
	}
	return ""
}

func (x *Strings) GetS11() string {
	if x != nil {
		return x.S11
	}
	return ""
}

// In addition to the validation code generated from the protobuf options,
// this message implements a custom validation. See `example_custom.go`
// in the same directory.
type Maps struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// you can put a constraint for map and a constraint for the value type as follows.
	Map1 map[string]int32 `protobuf:"bytes,1,rep,name=map1,proto3" json:"map1,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// or either one of them. The following enforces that the timestamp is set.
	Map2 map[string]*timestamppb.Timestamp `protobuf:"bytes,2,rep,name=map2,proto3" json:"map2,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// string values are normalized into the NFC form even if there's no rules specified.
	Map3 map[uint32]string `protobuf:"bytes,3,rep,name=map3,proto3" json:"map3,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// if the map key is a string, it is normalized into the NFC.
	// if the map vakue is a message, fields in it are always normalized/validated.
	Map4          map[string]*Scalars `protobuf:"bytes,4,rep,name=map4,proto3" json:"map4,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Maps) Reset() {
	*x = Maps{}
	mi := &file_examples_validation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maps) ProtoMessage() {}

func (x *Maps) ProtoReflect() protoreflect.Message {
	mi := &file_examples_validation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maps.ProtoReflect.Descriptor instead.
func (*Maps) Descriptor() ([]byte, []int) {
	return file_examples_validation_proto_rawDescGZIP(), []int{5}
}

func (x *Maps) GetMap1() map[string]int32 {
	if x != nil {
		return x.Map1
	}
	return nil
}

func (x *Maps) GetMap2() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.Map2
	}
	return nil
}

func (x *Maps) GetMap3() map[uint32]string {
	if x != nil {
		return x.Map3
	}
	return nil
}

func (x *Maps) GetMap4() map[string]*Scalars {
	if x != nil {
		return x.Map4
	}
	return nil
}

type Enums struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enforces that `e1` is not the zero value.
	E1 Enums_Enum `protobuf:"varint,1,opt,name=e1,proto3,enum=examples.Enums_Enum" json:"e1,omitempty"`
	// enforces that `e2` is one of the defined enum value.
	E2 Enums_Enum `protobuf:"varint,2,opt,name=e2,proto3,enum=examples.Enums_Enum" json:"e2,omitempty"`
	// enforces that `e3` is one of the defined enum value other than zero.
	E3 []Enums_Enum `protobuf:"varint,3,rep,packed,name=e3,proto3,enum=examples.Enums_Enum" json:"e3,omitempty"`
	// enforces that `e4` is, if given, one of the defined enum value other than zero.
	E4            *Enums_Enum `protobuf:"varint,4,opt,name=e4,proto3,enum=examples.Enums_Enum,oneof" json:"e4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enums) Reset() {
	*x = Enums{}
	mi := &file_examples_validation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enums) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enums) ProtoMessage() {}

func (x *Enums) ProtoReflect() protoreflect.Message {
	mi := &file_examples_validation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enums.ProtoReflect.Descriptor instead.
func (*Enums) Descriptor() ([]byte, []int) {
	return file_examples_validation_proto_rawDescGZIP(), []int{6}
}

func (x *Enums) GetE1() Enums_Enum {
	if x != nil {
		return x.E1
	}
	return Enums_E_UNSPECIFIED
}

func (x *Enums) GetE2() Enums_Enum {
	if x != nil {
		return x.E2
	}
	return Enums_E_UNSPECIFIED
}

func (x *Enums) GetE3() []Enums_Enum {
	if x != nil {
		return x.E3
	}
	return nil
}

func (x *Enums) GetE4() Enums_Enum {
	if x != nil && x.E4 != nil {
		return *x.E4
	}
	return Enums_E_UNSPECIFIED
}

type Oneofs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to O1:
	//
	//	*Oneofs_Int32
	//	*Oneofs_String_
	O1 isOneofs_O1 `protobuf_oneof:"o1"`
	// Types that are valid to be assigned to O2:
	//
	//	*Oneofs_Ts
	//	*Oneofs_Bool
	O2            isOneofs_O2 `protobuf_oneof:"o2"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Oneofs) Reset() {
	*x = Oneofs{}
	mi := &file_examples_validation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Oneofs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oneofs) ProtoMessage() {}

func (x *Oneofs) ProtoReflect() protoreflect.Message {
	mi := &file_examples_validation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oneofs.ProtoReflect.Descriptor instead.
func (*Oneofs) Descriptor() ([]byte, []int) {
	return file_examples_validation_proto_rawDescGZIP(), []int{7}
}

func (x *Oneofs) GetO1() isOneofs_O1 {
	if x != nil {
		return x.O1
	}
	return nil
}

func (x *Oneofs) GetInt32() int32 {
	if x != nil {
		if x, ok := x.O1.(*Oneofs_Int32); ok {
			return x.Int32
		}
	}
	return 0
}

func (x *Oneofs) GetString_() string {
	if x != nil {
		if x, ok := x.O1.(*Oneofs_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *Oneofs) GetO2() isOneofs_O2 {
	if x != nil {
		return x.O2
	}
	return nil
}

func (x *Oneofs) GetTs() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.O2.(*Oneofs_Ts); ok {
			return x.Ts
		}
	}
	return nil
}

func (x *Oneofs) GetBool() bool {
	if x != nil {
		if x, ok := x.O2.(*Oneofs_Bool); ok {
			return x.Bool
		}
	}
	return false
}

type isOneofs_O1 interface {
	isOneofs_O1()
}

type Oneofs_Int32 struct {
	Int32 int32 `protobuf:"varint,1,opt,name=int32,proto3,oneof"`
}

type Oneofs_String_ struct {
	String_ string `protobuf:"bytes,2,opt,name=string,proto3,oneof"`
}

func (*Oneofs_Int32) isOneofs_O1() {}

func (*Oneofs_String_) isOneofs_O1() {}

type isOneofs_O2 interface {
	isOneofs_O2()
}

type Oneofs_Ts struct {
	Ts *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3,oneof"`
}

type Oneofs_Bool struct {
	Bool bool `protobuf:"varint,4,opt,name=bool,proto3,oneof"`
}

func (*Oneofs_Ts) isOneofs_O2() {}

func (*Oneofs_Bool) isOneofs_O2() {}

// message type fields are normalized/validated recursively.
type Composed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enforces that `ignored` is set.
	Ignored *Ignored `protobuf:"bytes,1,opt,name=ignored,proto3" json:"ignored,omitempty"`
	Scalars *Scalars `protobuf:"bytes,2,opt,name=scalars,proto3" json:"scalars,omitempty"`
	Maps    []*Maps  `protobuf:"bytes,3,rep,name=maps,proto3" json:"maps,omitempty"`
	// enforces that all messages in `enums` are set.
	Enums         []*Enums `protobuf:"bytes,4,rep,name=enums,proto3" json:"enums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Composed) Reset() {
	*x = Composed{}
	mi := &file_examples_validation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Composed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Composed) ProtoMessage() {}

func (x *Composed) ProtoReflect() protoreflect.Message {
	mi := &file_examples_validation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Composed.ProtoReflect.Descriptor instead.
func (*Composed) Descriptor() ([]byte, []int) {
	return file_examples_validation_proto_rawDescGZIP(), []int{8}
}

func (x *Composed) GetIgnored() *Ignored {
	if x != nil {
		return x.Ignored
	}
	return nil
}

func (x *Composed) GetScalars() *Scalars {
	if x != nil {
		return x.Scalars
	}
	return nil
}

func (x *Composed) GetMaps() []*Maps {
	if x != nil {
		return x.Maps
	}
	return nil
}

func (x *Composed) GetEnums() []*Enums {
	if x != nil {
		return x.Enums
	}
	return nil
}

type Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inner         *Nested_Inner          `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested) Reset() {
	*x = Nested{}
	mi := &file_examples_validation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_examples_validation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_examples_validation_proto_rawDescGZIP(), []int{9}
}

func (x *Nested) GetInner() *Nested_Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

// Inner will also be validated.
type Nested_Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32         int32                  `protobuf:"varint,1,opt,name=int32,proto3" json:"int32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested_Inner) Reset() {
	*x = Nested_Inner{}
	mi := &file_examples_validation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested_Inner) ProtoMessage() {}

func (x *Nested_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_examples_validation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested_Inner.ProtoReflect.Descriptor instead.
func (*Nested_Inner) Descriptor() ([]byte, []int) {
	return file_examples_validation_proto_rawDescGZIP(), []int{9, 0}
}

func (x *Nested_Inner) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

var File_examples_validation_proto protoreflect.FileDescriptor

const file_examples_validation_proto_rawDesc = "" +
	"\n" +
	"\x19examples/validation.proto\x12\bexamples\x1a\x1dcybozu/validate/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\aIgnored\x12\x10\n" +
	"\x03foo\x18\x01 \x01(\tR\x03foo\x12\x19\n" +
	"\x03bar\x18\x02 \x01(\x05B\a\xdaI\x04\x1a\x02\bdR\x03bar:\x03\xd8I\x01\"\x94\x04\n" +
	"\aScalars\x12 \n" +
	"\x05float\x18\x01 \x01(\x02B\n" +
	"\xdaI\a\n" +
	"\x05\r\xcd\xccL@R\x05float\x12&\n" +
	"\x06double\x18\x02 \x01(\x01B\x0e\xdaI\v\x12\t\x19\x9a\x99\x99\x99\x99\x99\t@R\x06double\x12&\n" +
	"\x05int32\x18\x03 \x01(\x05B\x10\xdaI\r\x1a\v\x10\xfd\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x05int32\x12\x1d\n" +
	"\x05int64\x18\x04 \x01(\x03B\a\xdaI\x04\"\x02 \x01R\x05int64\x12!\n" +
	"\x06uint32\x18\x05 \x01(\rB\t\xdaI\x06*\x04\b\x05\x18\x01R\x06uint32\x12!\n" +
	"\x06uint64\x18\x06 \x01(\x04B\t\xdaI\x062\x04\x10\x05 \x01R\x06uint64\x12!\n" +
	"\x06sint32\x18\a \x01(\x11B\t\xdaI\x06:\x04\b\x05\x18\x01R\x06sint32\x12!\n" +
	"\x06sint64\x18\b \x01(\x12B\t\xdaI\x06B\x04\x10\x05 \x01R\x06sint64\x12#\n" +
	"\afixed32\x18\t \x01(\aB\t\xdaI\x06J\x04\b\x05\x18\x01R\afixed32\x12#\n" +
	"\afixed64\x18\n" +
	" \x01(\x06B\t\xdaI\x06R\x04\b\x05\x18\x01R\afixed64\x12%\n" +
	"\bsfixed32\x18\v \x01(\x0fB\t\xdaI\x06Z\x04\b\x05\x18\x01R\bsfixed32\x12%\n" +
	"\bsfixed64\x18\f \x01(\x10B\t\xdaI\x06b\x04\b\x05\x18\x01R\bsfixed64\x12\x12\n" +
	"\x04bool\x18\r \x01(\bR\x04bool\x12!\n" +
	"\x06string\x18\x0e \x01(\tB\t\xdaI\x06r\x04\x10\x01\x18\x03R\x06string\x12\x1d\n" +
	"\x05bytes\x18\x0f \x01(\fB\a\xdaI\x04z\x02 \n" +
	"R\x05bytes\"\x8c\x06\n" +
	"\x0fOptionalScalars\x12%\n" +
	"\x05float\x18\x01 \x01(\x02B\n" +
	"\xdaI\a\n" +
	"\x05\r\xcd\xccL@H\x00R\x05float\x88\x01\x01\x12+\n" +
	"\x06double\x18\x02 \x01(\x01B\x0e\xdaI\v\x12\t\x19\x9a\x99\x99\x99\x99\x99\t@H\x01R\x06double\x88\x01\x01\x12+\n" +
	"\x05int32\x18\x03 \x01(\x05B\x10\xdaI\r\x1a\v\x10\xfd\xff\xff\xff\xff\xff\xff\xff\xff\x01H\x02R\x05int32\x88\x01\x01\x12\"\n" +
	"\x05int64\x18\x04 \x01(\x03B\a\xdaI\x04\"\x02 \x01H\x03R\x05int64\x88\x01\x01\x12&\n" +
	"\x06uint32\x18\x05 \x01(\rB\t\xdaI\x06*\x04\b\x05\x18\x01H\x04R\x06uint32\x88\x01\x01\x12&\n" +
	"\x06uint64\x18\x06 \x01(\x04B\t\xdaI\x062\x04\x10\x05 \x01H\x05R\x06uint64\x88\x01\x01\x12&\n" +
	"\x06sint32\x18\a \x01(\x11B\t\xdaI\x06:\x04\b\x05\x18\x01H\x06R\x06sint32\x88\x01\x01\x12&\n" +
	"\x06sint64\x18\b \x01(\x12B\t\xdaI\x06B\x04\x10\x05 \x01H\aR\x06sint64\x88\x01\x01\x12(\n" +
	"\afixed32\x18\t \x01(\aB\t\xdaI\x06J\x04\b\x05\x18\x01H\bR\afixed32\x88\x01\x01\x12(\n" +
	"\afixed64\x18\n" +
	" \x01(\x06B\t\xdaI\x06R\x04\x10\x05 \x01H\tR\afixed64\x88\x01\x01\x12*\n" +
	"\bsfixed32\x18\v \x01(\x0fB\t\xdaI\x06Z\x04\b\x05\x18\x01H\n" +
	"R\bsfixed32\x88\x01\x01\x12*\n" +
	"\bsfixed64\x18\f \x01(\x10B\t\xdaI\x06b\x04\x10\x05 \x01H\vR\bsfixed64\x88\x01\x01\x12\x17\n" +
	"\x04bool\x18\r \x01(\bH\fR\x04bool\x88\x01\x01\x12&\n" +
	"\x06string\x18\x0e \x01(\tB\t\xdaI\x06r\x04\x10\x01\x18\x03H\rR\x06string\x88\x01\x01\x12\"\n" +
	"\x05bytes\x18\x0f \x01(\fB\a\xdaI\x04z\x02 \n" +
	"H\x0eR\x05bytes\x88\x01\x01B\b\n" +
	"\x06_floatB\t\n" +
	"\a_doubleB\b\n" +
	"\x06_int32B\b\n" +
	"\x06_int64B\t\n" +
	"\a_uint32B\t\n" +
	"\a_uint64B\t\n" +
	"\a_sint32B\t\n" +
	"\a_sint64B\n" +
	"\n" +
	"\b_fixed32B\n" +
	"\n" +
	"\b_fixed64B\v\n" +
	"\t_sfixed32B\v\n" +
	"\t_sfixed64B\a\n" +
	"\x05_boolB\t\n" +
	"\a_stringB\b\n" +
	"\x06_bytes\"\x87\x01\n" +
	"\x0fRepeatedScalars\x12%\n" +
	"\x05float\x18\x01 \x03(\x02B\x0f\xdaI\f\n" +
	"\x05\r\xcd\xccL@\xc2>\x02\b\x01R\x05float\x12+\n" +
	"\x06double\x18\x02 \x03(\x01B\x13\xdaI\x10\x12\t\x19\x9a\x99\x99\x99\x99\x99\t@\xc2>\x02\x10\x03R\x06double\x12 \n" +
	"\x06string\x18\x03 \x03(\tB\b\xdaI\x05\xc2>\x02\b\x02R\x06string\"\xa0\x02\n" +
	"\aStrings\x12\x0e\n" +
	"\x02s1\x18\x01 \x01(\tR\x02s1\x12\x17\n" +
	"\x02s2\x18\x02 \x01(\tB\a\xdaI\x04r\x02\b\x01R\x02s2\x12\x19\n" +
	"\x02s3\x18\x03 \x01(\tB\t\xdaI\x06r\x04\x10\x01\x18\n" +
	"R\x02s3\x12\x17\n" +
	"\x02s4\x18\x04 \x01(\tB\a\xdaI\x04r\x02\bdR\x02s4\x12\x17\n" +
	"\x02s5\x18\x05 \x01(\tB\a\xdaI\x04r\x02\beR\x02s5\x12\x17\n" +
	"\x02s6\x18\x06 \x01(\tB\a\xdaI\x04r\x02\bfR\x02s6\x12\x17\n" +
	"\x02s7\x18\a \x01(\tB\a\xdaI\x04r\x02\bgR\x02s7\x12\x1b\n" +
	"\x02s8\x18\b \x01(\tB\v\xdaI\br\x06*\x04^abcR\x02s8\x12\x18\n" +
	"\x02s9\x18\t \x01(\tB\b\xdaI\x05r\x03\xa0\x06\x01R\x02s9\x12\x1a\n" +
	"\x03s10\x18\n" +
	" \x01(\tB\b\xdaI\x05r\x03\xa8\x06\x01R\x03s10\x12\x1a\n" +
	"\x03s11\x18\v \x01(\tB\b\xdaI\x05r\x03\xb0\x06\x01R\x03s11\"\xe9\x03\n" +
	"\x04Maps\x12:\n" +
	"\x04map1\x18\x01 \x03(\v2\x18.examples.Maps.Map1EntryB\f\xdaI\t\x1a\x02\x18\x03\xca>\x02\b\x01R\x04map1\x126\n" +
	"\x04map2\x18\x02 \x03(\v2\x18.examples.Maps.Map2EntryB\b\xdaI\x05\x8a\x01\x02\b\x01R\x04map2\x12,\n" +
	"\x04map3\x18\x03 \x03(\v2\x18.examples.Maps.Map3EntryR\x04map3\x12,\n" +
	"\x04map4\x18\x04 \x03(\v2\x18.examples.Maps.Map4EntryR\x04map4\x1a7\n" +
	"\tMap1Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aS\n" +
	"\tMap2Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x01\x1a7\n" +
	"\tMap3Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aJ\n" +
	"\tMap4Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.examples.ScalarsR\x05value:\x028\x01\"\x8f\x02\n" +
	"\x05Enums\x12.\n" +
	"\x02e1\x18\x01 \x01(\x0e2\x14.examples.Enums.EnumB\b\xdaI\x05\x82\x01\x02\b\x01R\x02e1\x12.\n" +
	"\x02e2\x18\x02 \x01(\x0e2\x14.examples.Enums.EnumB\b\xdaI\x05\x82\x01\x02\x10\x01R\x02e2\x123\n" +
	"\x02e3\x18\x03 \x03(\x0e2\x14.examples.Enums.EnumB\r\xdaI\n" +
	"\x82\x01\x02\b\x01\xc2>\x02\b\x02R\x02e3\x125\n" +
	"\x02e4\x18\x04 \x01(\x0e2\x14.examples.Enums.EnumB\n" +
	"\xdaI\a\x82\x01\x04\b\x01\x10\x01H\x00R\x02e4\x88\x01\x01\"3\n" +
	"\x04Enum\x12\x11\n" +
	"\rE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06E_VAL1\x10\x01\x12\f\n" +
	"\bE_VAL100\x10dB\x05\n" +
	"\x03_e4\"\xa1\x01\n" +
	"\x06Oneofs\x12(\n" +
	"\x05int32\x18\x01 \x01(\x05B\x10\xdaI\r\x1a\v\x10\xfd\xff\xff\xff\xff\xff\xff\xff\xff\x01H\x00R\x05int32\x12\x18\n" +
	"\x06string\x18\x02 \x01(\tH\x00R\x06string\x12,\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02ts\x12\x14\n" +
	"\x04bool\x18\x04 \x01(\bH\x01R\x04boolB\x04\n" +
	"\x02o1B\t\n" +
	"\x02o2\x12\x03\xd8I\x01\"\xc3\x01\n" +
	"\bComposed\x125\n" +
	"\aignored\x18\x01 \x01(\v2\x11.examples.IgnoredB\b\xdaI\x05\x8a\x01\x02\b\x01R\aignored\x12+\n" +
	"\ascalars\x18\x02 \x01(\v2\x11.examples.ScalarsR\ascalars\x12\"\n" +
	"\x04maps\x18\x03 \x03(\v2\x0e.examples.MapsR\x04maps\x12/\n" +
	"\x05enums\x18\x04 \x03(\v2\x0f.examples.EnumsB\b\xdaI\x05\x8a\x01\x02\b\x01R\x05enums\"h\n" +
	"\x06Nested\x126\n" +
	"\x05inner\x18\x01 \x01(\v2\x16.examples.Nested.InnerB\b\xdaI\x05\x8a\x01\x02\b\x01R\x05inner\x1a&\n" +
	"\x05Inner\x12\x1d\n" +
	"\x05int32\x18\x01 \x01(\x05B\a\xdaI\x04\x1a\x02\x18\x03R\x05int32B\"Z github.com/cybozu/proto/examplesb\x06proto3"

var (
	file_examples_validation_proto_rawDescOnce sync.Once
	file_examples_validation_proto_rawDescData []byte
)

func file_examples_validation_proto_rawDescGZIP() []byte {
	file_examples_validation_proto_rawDescOnce.Do(func() {
		file_examples_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_validation_proto_rawDesc), len(file_examples_validation_proto_rawDesc)))
	})
	return file_examples_validation_proto_rawDescData
}

var file_examples_validation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_examples_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_examples_validation_proto_goTypes = []any{
	(Enums_Enum)(0),               // 0: examples.Enums.Enum
	(*Ignored)(nil),               // 1: examples.Ignored
	(*Scalars)(nil),               // 2: examples.Scalars
	(*OptionalScalars)(nil),       // 3: examples.OptionalScalars
	(*RepeatedScalars)(nil),       // 4: examples.RepeatedScalars
	(*Strings)(nil),               // 5: examples.Strings
	(*Maps)(nil),                  // 6: examples.Maps
	(*Enums)(nil),                 // 7: examples.Enums
	(*Oneofs)(nil),                // 8: examples.Oneofs
	(*Composed)(nil),              // 9: examples.Composed
	(*Nested)(nil),                // 10: examples.Nested
	nil,                           // 11: examples.Maps.Map1Entry
	nil,                           // 12: examples.Maps.Map2Entry
	nil,                           // 13: examples.Maps.Map3Entry
	nil,                           // 14: examples.Maps.Map4Entry
	(*Nested_Inner)(nil),          // 15: examples.Nested.Inner
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_examples_validation_proto_depIdxs = []int32{
	11, // 0: examples.Maps.map1:type_name -> examples.Maps.Map1Entry
	12, // 1: examples.Maps.map2:type_name -> examples.Maps.Map2Entry
	13, // 2: examples.Maps.map3:type_name -> examples.Maps.Map3Entry
	14, // 3: examples.Maps.map4:type_name -> examples.Maps.Map4Entry
	0,  // 4: examples.Enums.e1:type_name -> examples.Enums.Enum
	0,  // 5: examples.Enums.e2:type_name -> examples.Enums.Enum
	0,  // 6: examples.Enums.e3:type_name -> examples.Enums.Enum
	0,  // 7: examples.Enums.e4:type_name -> examples.Enums.Enum
	16, // 8: examples.Oneofs.ts:type_name -> google.protobuf.Timestamp
	1,  // 9: examples.Composed.ignored:type_name -> examples.Ignored
	2,  // 10: examples.Composed.scalars:type_name -> examples.Scalars
	6,  // 11: examples.Composed.maps:type_name -> examples.Maps
	7,  // 12: examples.Composed.enums:type_name -> examples.Enums
	15, // 13: examples.Nested.inner:type_name -> examples.Nested.Inner
	16, // 14: examples.Maps.Map2Entry.value:type_name -> google.protobuf.Timestamp
	2,  // 15: examples.Maps.Map4Entry.value:type_name -> examples.Scalars
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_examples_validation_proto_init() }
func file_examples_validation_proto_init() {
	if File_examples_validation_proto != nil {
		return
	}
	file_examples_validation_proto_msgTypes[2].OneofWrappers = []any{}
	file_examples_validation_proto_msgTypes[6].OneofWrappers = []any{}
	file_examples_validation_proto_msgTypes[7].OneofWrappers = []any{
		(*Oneofs_Int32)(nil),
		(*Oneofs_String_)(nil),
		(*Oneofs_Ts)(nil),
		(*Oneofs_Bool)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_validation_proto_rawDesc), len(file_examples_validation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_validation_proto_goTypes,
		DependencyIndexes: file_examples_validation_proto_depIdxs,
		EnumInfos:         file_examples_validation_proto_enumTypes,
		MessageInfos:      file_examples_validation_proto_msgTypes,
	}.Build()
	File_examples_validation_proto = out.File
	file_examples_validation_proto_goTypes = nil
	file_examples_validation_proto_depIdxs = nil
}
